import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { HeroSection } from "../components/ui/Hero";
import { ArtistsSection } from "../components/ui/Artists";
import { ArtSection } from "../components/ui/ArtPieces";
import { AboutSection } from "../components/ui/About";
import { Footer } from "../components/footer";
import { CategorySection } from "../components/ui/Category";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <HeroSection />
        <ArtistsSection />
        <ArtSection />
        <CategorySection />
        <AboutSection />
      </main>

      <Footer />
    </div>
  );
};

export default HomePage;
